### PR TITLE
updated .load, .loadRoot, rootTemplate and preTemplates to allow for supplying buffers in addition to file paths.

### LINKED ISSUE #108: Read files from memory instead of from a directory?
I am trying to use this library in an AWS Lambda environment, so I don't have access to the file system. I'm generating a pptx file with PptxGenJs, then trying to add master slides from our corporate template that I'm reading in from s3. Is there a supported way to read a file from memory rather than a local directory?

i.e.

```javaScript
import pptxgen from "pptxgenjs"
import Automizer from "pptx-automizer"
import { S3Client, GetObjectCommand } from "@aws-sdk/client-s3"

const pptx = new pptxgen()
//build presentation with pptxgen...

const s3Client = new S3Client()

const response = await s3Client.send(
  new GetObjectCommand({ Bucket: templateBucket, Key: templateKey })
)

const template = await response.Body?.transformToByteArray()

const myPresentation = await pptx.write({
    outputType: "nodebuffer"
})

const automizer = new Automizer()

const pres = automizer.loadRoot(template)
    .load(template, "template")
    .load(myPresentation, "myPres")
    
//...
```

I can see that `.load` and `.loadRoot` both only take a file path currently.

- Is there another method that accepts a `Buffer` or `Uint8Array`? 
  - If not, would you be open to accepting a PR that enables this behavior?
    - If so, would you prefer to overload the `.load` / `.loadRoot` methods so they could also accept binary?
    - Or would it be better to add new methods?

### PR DESCRIPTION
**Pull request by mikemeerschaert**
This enables loading files from a buffer in addition to a file path. Resolves #108

### CODE REVIEW

**Comment by singerla** [comment]
This is awsome! Thank you so much!

**Comment by singerla** [comment]
I will also need to update readme. I'll come back to this tomorrow!

**Comment by mikemeerschaert** [comment]
Thanks! I also noticed a minor issue with logging where sometimes it prints the full byte array to the console because it still treats the file like the file path, but i haven't had time to create a way to reproduce it and track it down. I'll work on it Monday (I'm in PST) and update the branch when I figure out how to resolve!

**Comment by singerla** [comment]
The full byte array in console might have been caused by automizer.getLocation();

**Review by singerla — APPROVED** [review]
Thanks a lot for improving our library!

**Pull request merged**
