### PR TITLE
Add ability to set Bullet Text content from array

### PR DESCRIPTION
**Pull request by jrking4**

### CODE REVIEW

**Review by singerla — APPROVED** [review]
This is very cool and useful. Thanks a lot.

**Comment by jrking4** [comment]
your welcome.  I had one quick question on the library.  

-Im getting an instance where one of my templates is not getting updated with the new XML. It just ignores the modify commmand completly. The command gets run, but the XML is never updated. is there some helpful tips you have to help debug this, or some aspect of the library that can help?

**Comment by singerla** [comment]
Sometimes, I'm doing `XmlHelper.dump` before and after the modification. If the modification is visible in the second dump, but there's no effect in pptx, you can check for e.g. a forgotten `await`.

**Comment by jrking4** [comment]
thanks i will give that a shot!

**Comment by jrking4** [comment]
Yes so whats strange is the template im using, even a simple operation like "setText" 
`slide.modifyElement(
     'Body',
     ModifyTextHelper.setText('This is my text'),
     //modify.setBulletList(['first line', 'second line', 'third line']),
);`

does not seem to have any effect.  the XML dump and console logs show the new XML. but the final file shows nothing

**Comment by jrking4** [comment]
OK. i found the bug.  so whats happening is if you run 
`slide.modifyElement( 'Body', ModifyTextHelper.setText('This is my text') );`

and then later loop through the text elements
```  const elementIds = await slide.getAllElements();
                    for (const elementId of elementIds) {
                        if (elementId.hasTextBody) {
                         slide.modifyElement(
                                        elementId.name,
                                        modify.replaceText(
                                            [
                                                {replace: 'headline', by: {text: slideItem.headline}}
                                            ],
                                            {
                                                openingTag: '{',
                                                closingTag: '}',
                                            },
                                        ),
                                    );
                        }

```

the library seems to reset any of those text fields

**Comment by singerla** [comment]
You are welcome to open a separate issue if you'd like to go deeper into this. Thanks for investigating!

**Pull request merged**
